// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Shared from "ocaml-nix-demo-shared/res/shared.mjs";

Shared.log({
      text: "hello world"
    });

export {
  
}
/*  Not a pure module */
